# Generated by Django 5.2.7 on 2025-11-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalspeciality',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
